FROM ubuntu:16.04
LABEL maintainer="garrett.rudisill@gmail.com"

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install htop

ADD package_notes.txt /
RUN apt-get update && apt-get install $(grep -vE "^\s*#" package_notes.txt  | tr "\n" " ") -y

# Ensure ssh toolkit is installed
RUN apt-get -y install openssh-client

# Add script which will get all data necessary for the BlueSky Job
ADD create_bluesky_container.sh /

# Run the script.
CMD bash create_bluesky_container.sh