FROM ubuntu:16.04
MAINTAINER Garrett Rudisill garrett.rudisill@gmail.com

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install htop
RUN apt-get install python -y
RUN apt-get install gfortran -y

ADD package_notes.txt /
RUN apt-get update && apt-get install $(grep -vE "^\s*#" package_notes.txt  | tr "\n" " ") -y



ADD hi.py /
ADD testsh.sh /
ADD ftest.f90 /

CMD bash testsh.sh